name: ci-vsix

on:
  push:
    branches: [main]
    paths:
      - 'MyVsix/**'
      - '.github/workflows/ci-vsix.yml'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-sign-vsix:
    strategy:
      matrix:
        os: [windows-2025, windows-2022, windows-latest]
    runs-on: ${{ matrix.os }}

    name: Build and sign VSIX on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Azure login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Sign VSIX with Artifact Signing
        uses: azure/artifact-signing-action@28e296df76229fba6a081e67e3eca87e3d5da360
        with:
          endpoint: https://eus.codesigning.azure.net/
          signing-account-name: jaxelr
          certificate-profile-name: jaxelr-pt
          files-folder: ${{ github.workspace }}/MyVsix
          files-folder-filter: vsix
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v6
        with:
          name: MyVsix-${{ matrix.os }}
          path: ${{ github.workspace }}/MyVsix
